### ISSUE TITLE
raise_on_failure=false not giving fire and forget performance

### ISSUE THREAD

**Issue by ryanwi** [emque/emque-producing#39]
For high load web applications that are publishing a message (or messages) with `raise_on_failure=false` for each web app request, there is a significant performance impact when a queue is receiving those messages. When there is no queue receiving the messages, there is no performance impact.

**Comment by knappe** [comment]
A couple of questions arise:
- http://reference.rubybunny.info/Bunny/Channel.html#wait_for_confirms-instance_method states that it will block until _all_ unack'd messages are confirmed.  This could be the source of significant latency if we're blocking one thread and another thread attempts to publish and also has a message that needs to confirm.  This thread too would then block as well.
- Once `confirm_select` is set on a channel, does it retain that setting?  It looks like we're taking that connection and returning it to the pool.  Could it be that all subsequent messages sent using that channel are also getting confirmed?
- Maybe I'm missing something, but we're never checking `raise_on_failure` before marking a channel as `confirm_select` https://github.com/emque/emque-producing/blob/master/lib/emque/producing/publisher/rabbitmq.rb#L31.  I'll need to explore if we can pause in message delivery and check if the channel is set to expect confirms for messages with `raise_on_failure` set to false

**Comment by ryanwi** [comment]
> states that it will block until all unack'd messages are confirmed. This could be the source of significant latency if we're blocking one thread and another thread attempts to publish and also has a message that needs to confirm. This thread too would then block as well.

We're not publishing through threads from the web apps currently. But yeah, it does sound like a pitfall.

> Once confirm_select is set on a channel, does it retain that setting? It looks like we're taking that connection and returning it to the pool. Could it be that all subsequent messages sent using that channel are also getting confirmed?

Good question, it appears so[1]
```
From this moment on, every message published on this channel will cause the channel's publisher index (message counter) to be incremented. It is possible to access the index using Bunny::Channel#next_publish_seq_no method. To check whether the channel is in confirmation mode, use the Bunny::Channel#using_publisher_confirmations? method:
```

> Maybe I'm missing something, but we're never checking raise_on_failure before marking a channel as confirm_select https://github.com/emque/emque-producing/blob/master/lib/emque/producing/publisher/rabbitmq.rb#L31. 

You are not missing anything here. Every RabbitMQ message is published through the confirm_select to determine if it succeeded or not, regardless of the `raise_on_failure`. The `raise_on_failure` is checked in the Emque::Message instance [2].


all in all, it still kind of strikes me as having 2 distinct `publish` paths, one for critical that does the waiting for confirmation and and one for fire and forget.


[1] http://rubybunny.info/articles/extensions.html
[2] https://github.com/emque/emque-producing/blob/fc3f43b5f26d7d0e26e513cff0165358c9340eae/lib/emque/producing/message/message.rb#L145
