### ISSUE TITLE
Memoize socket hostname call in Message

### ISSUE THREAD

**Issue by randy-girard** [emque/emque-producing#46]
There was an issue in local development environment where the hosts file did not include an IPv6 entry for the hostname, cause this call to take roughly 5 seconds to execute. We should memoize this value so we do not do the look up every time.

https://github.com/emque/emque-producing/blob/master/lib/emque/producing/message/message.rb#L169

**Comment by ryanwi** [comment]
Ah ha, nice find. Made a PR to see if that will help.
